name: Build and Commit JAR

on:
  [push, pull_request, workflow_dispatch]

env:
  MINECRAFT_VERSION: 1.20.1
  JAVA_VERSION: 17
  VERSION: 0.0+1.20.1
  JAR_DIRECTORY: mod-jars  # Directory in the repo to store the JAR file
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN.TOKEN }}  # Reference the secret within the GITHUB_TOKEN environment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Create JAR Directory
        run: mkdir -p ${{ env.JAR_DIRECTORY }}

      - name: Move JAR to Repository Directory
        run: mv build/libs/*.jar ${{ env.JAR_DIRECTORY }}/

      - name: Commit and Push JAR
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Add mod JAR file ${{ env.VERSION }}"
          add: ${{ env.JAR_DIRECTORY }}/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN.TOKEN }}  # Use the secret here
