name: Build and Publish to GitHub Releases

on:
  [pull_request, workflow_dispatch]

env:
  MINECRAFT_VERSION: 1.19.2
  JAVA_VERSION: 17
  VERSION: 1.1.0+1.19.2
  RELEASE_NAME: Example Mod 1.1.0 for Minecraft 1.19.2
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure this is added to repository secrets

permissions:
  contents: write
  packages: write
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: mod-jar
          path: build/libs/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v3
        with:
          name: mod-jar
